GET https://jsonplaceholder.typicode.com/posts/

###
GET http://localhost:3000/api/posts

###
DELETE http://localhost:3000/api/posts/1

###
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "userId": 4,
  "title": "hi",
  "body": "hello"
}

###
PUT http://localhost:3000/api/posts/7
Content-Type: application/json

{
  "id": 7,
  "userId": 4,
  "title": "hi - updated",
  "body": "hello - updated"
}

